# Generated by Django 3.1 on 2020-02-06 23:01

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='data_nascita',
            new_name='birthday_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gnr',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='ingredientiricette',
            name='quantita',
            field=models.CharField(help_text='Quantità', max_length=200),
        ),
        migrations.AlterField(
            model_name='ricetta',
            name='nazionalita',
            field=django_countries.fields.CountryField(help_text='Nazionalità', max_length=2),
        ),
    ]
