# Generated by Django 3.1 on 2020-02-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20200207_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ricetta',
            name='immagine',
            field=models.ImageField(default='default.jpg', upload_to='ricette/'),
        ),
    ]
