# Generated by Django 3.1 on 2020-02-07 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20200207_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricetta',
            name='autore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
