# Generated by Django 3.1 on 2020-02-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20200211_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='calorie',
            field=models.IntegerField(default='0', verbose_name='Calorie'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nome',
            field=models.CharField(default='Ingrediente', max_length=200, verbose_name='Nome'),
        ),
    ]
