# Generated by Django 3.1 on 2020-02-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_auto_20200211_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientiricette',
            name='ingrediente',
            field=models.ManyToManyField(to='catalogo.Ingrediente'),
        ),
        migrations.AlterField(
            model_name='ingredientiricette',
            name='quantita',
            field=models.CharField(max_length=200, verbose_name='Quantità'),
        ),
        migrations.AlterField(
            model_name='ingredientiricette',
            name='ricetta',
            field=models.ManyToManyField(to='catalogo.Ricetta'),
        ),
    ]
