# Generated by Django 3.1 on 2020-02-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_auto_20200211_1937'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientiricette',
            unique_together={('ingrediente', 'ricetta')},
        ),
    ]
