# Generated by Django 3.1 on 2020-02-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_auto_20200211_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthday_date',
            new_name='birth_date',
        ),
    ]
