# Generated by Django 3.1 on 2020-02-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_auto_20200211_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data di nascita'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Maschio', 'Maschio'), ('Femmina', 'Femmina'), ('Non dichiarato', 'Non dichiarato')], default='N', max_length=15, verbose_name='Genere'),
        ),
    ]
