# Generated by Django 3.1 on 2020-02-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_auto_20200212_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Maschio', 'Maschio'), ('Femmina', 'Femmina'), ('Non dichiarato', 'Non dichiarato')], default='Non dichiarato', max_length=15, verbose_name='Genere'),
        ),
    ]
